# Compositional analysis

```{r load_data_composition, warning=FALSE, comments="", message=FALSE}
load("data/data.Rdata")
extra_metadata <- read_csv("data/Bombina_microbiome_metadata.csv") %>% 
  rename(animal=sample) %>% 
  rename(sample=EHI_code)
sample_metadata <- sample_metadata %>% 
  left_join(., extra_metadata, by="sample")

genome_counts_filt <- genome_counts_filt %>%
  select(one_of(c("genome",sample_metadata$sample)))%>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0))

genome_metadata <- genome_metadata %>%
  semi_join(., genome_counts_filt, by = "genome") %>%
  arrange(match(genome,genome_counts_filt$genome))

genome_tree <- keep.tip(genome_tree, tip=genome_metadata$genome)

phylum_colors <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
    right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    arrange(match(genome, genome_tree$tip.label)) %>%
    select(phylum, colors) %>% 
    unique() %>%
    arrange(phylum) %>%
    pull(colors, name=phylum)
```

```{r}
sample_metadata %>% 
  group_by(region, Bd_status, sex) %>% 
  summarise(count=n())
```

```{r barplot_individuals, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
genome_counts_filt %>%
  mutate_at(vars(-genome),~./sum(.)) %>% #apply TSS nornalisation
  pivot_longer(-genome, names_to = "sample", values_to = "count") %>% #reduce to minimum number of columns
  left_join(., genome_metadata, by = join_by(genome == genome)) %>% #append genome metadata
  left_join(., sample_metadata, by = join_by(sample == sample)) %>% #append sample metadata
  filter(!is.na(count)) %>%
  ggplot(aes(y=count,x=sample, fill=phylum, group=phylum)) + #grouping enables keeping the same sorting of taxonomic units
    geom_bar(stat="identity", colour="white", linewidth=0.1) + 
    scale_fill_manual(values=phylum_colors) +
  facet_grid(~ Bd_status, scale="free", space="free")+
    guides(fill = guide_legend(ncol = 1)) +
    theme(
          axis.title.x = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_rect(fill = "white"),
    strip.text = element_text(size = 8, lineheight = 0.6),
    strip.placement = "outside",
    axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.line = element_line(linewidth = 0.5, linetype = "solid", colour = "black")) +
   labs(fill="Phylum",y = "Relative abundance",x="Samples")
```


## Phylum relative abundances

```{r taxonomy_phylum_summary, warning=FALSE, comments="", message=FALSE}
phylum_summary <- genome_counts_filt %>%
  mutate_at(vars(-genome),~./sum(.)) %>% 
  pivot_longer(-genome, names_to = "sample", values_to = "count") %>%
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  left_join(genome_metadata, by = join_by(genome == genome)) %>%
  group_by(sample,phylum,Bd_status) %>%
  summarise(relabun=sum(count))
```

```{r taxonomy_phylum_summary_origin, warning=FALSE, comments="", message=FALSE}
phylum_summary %>%
  group_by(phylum) %>%
  summarise(
    total_mean = mean(relabun * 100, na.rm = T),
    total_sd = sd(relabun * 100, na.rm = T),
    positive_mean = mean(relabun[Bd_status == "Bd_positive"] * 100, na.rm = T),
    positive_sd = sd(relabun[Bd_status == "Bd_positive"] * 100, na.rm = T),
    negative_mean = mean(relabun[Bd_status == "Bd_negative"] * 100, na.rm = T),
    negative_sd = sd(relabun[Bd_status == "Bd_negative"] * 100, na.rm = T)
  ) %>%
  mutate(
    total = str_c(round(total_mean, 3), "±", round(total_sd, 3)),
    Positive = str_c(round(positive_mean, 3), "±", round(positive_sd, 3)),
    Negative = str_c(round(negative_mean, 3), "±", round(negative_sd, 3))
    ) %>%
  arrange(-total_mean) %>%
  dplyr::select(phylum, total, Positive, Negative) %>%
  tt()
```




