# Alpha diversity

```{r load_data_diversity, warning=FALSE, comments="", message=FALSE}
set.seed(1234) 

load("data/data.Rdata")

extra_metadata <- read_csv("data/Bombina_microbiome_metadata.csv") %>% 
  rename(animal=sample) %>% 
  rename(sample=EHI_code)
sample_metadata <- sample_metadata %>% 
  left_join(., extra_metadata, by="sample")

genome_counts_filt <- genome_counts_filt %>%
  select(one_of(c("genome",sample_metadata$sample)))%>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0))

genome_metadata <- genome_metadata %>%
  semi_join(., genome_counts_filt, by = "genome") %>%
  arrange(match(genome,genome_counts_filt$genome))

genome_tree <- keep.tip(genome_tree, tip=genome_metadata$genome)

phylum_colors <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
    right_join(genome_metadata, by=join_by(phylum == phylum)) %>%
    arrange(match(genome, genome_tree$tip.label)) %>%
    select(phylum, colors) %>% 
    unique() %>%
    arrange(phylum) %>%
    pull(colors, name=phylum)
```
```{r alpha_div, comment="", message=FALSE, warning=FALSE}
richness <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 0) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(richness = 1) %>%
  rownames_to_column(var = "sample")

neutral <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(neutral = 1) %>%
  rownames_to_column(var = "sample")

phylogenetic <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, tree = genome_tree) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(phylogenetic = 1) %>%
  rownames_to_column(var = "sample")

# Aggregate basal GIFT into elements
dist <- genome_gifts %>%
  to.elements(., GIFT_db) %>%
  traits2dist(., method = "gower")

functional <- genome_counts_filt %>%
  filter(genome %in% labels(dist)[[1]]) %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, dist = dist) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(functional = 1) %>%
  rownames_to_column(var = "sample") %>%
  mutate(functional = if_else(is.nan(functional), 1, functional))

# Merge all metrics
alpha_div <- richness %>%
  full_join(neutral, by = join_by(sample == sample)) %>%
  full_join(phylogenetic, by = join_by(sample == sample)) %>%
  full_join(functional, by = join_by(sample == sample))
```
```{r alpha_plots_loc, fig.height=5, fig.width=12, fig.fullwidth=TRUE}
alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  mutate(metric=factor(metric,levels=c("richness","neutral","phylogenetic", "functional"))) %>%
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  ggplot(aes(y = value, x = Bd_status, group=Bd_status, color=Bd_status, fill=Bd_status)) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  facet_wrap(. ~factor(metric, labels=c("richness" = "Richness", "neutral" = "Neutral", "phylogenetic" = "Phylogenetic", "functional"="Functional")), scales = "free", ncol = 5) +
  stat_compare_means(show.legend = FALSE) +
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size =12, lineheight = 0.6),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank()
  )
```

# Beta diversity

```{r beta_div, comment="", message=FALSE, warning=FALSE}
beta_q0n <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 0)

beta_q1n <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 1)

beta_q1p <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 1, tree = genome_tree)

beta_q1f <- genome_counts_filt %>%
  filter(genome %in% labels(dist)[[1]]) %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 1, dist = dist)
```

## Richness
```{r beta_div_nmds_richness, fig.height=7, fig.width=12, fig.fullwidth=TRUE}
beta_q0n$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  mutate(Bd_status=factor(Bd_status,levels=c("Bd_positive", "Bd_negative")))%>%
  group_by(Bd_status) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot(aes(x = NMDS1, y = NMDS2, color = Bd_status)) +
    geom_point(size = 3, alpha = 0.9) +
    geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.5, show.legend = FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(face = "bold", size = 12),
      panel.background = element_blank(),
      axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 14),
      legend.position = "right", legend.box = "vertical"
    ) +
  labs(color='Bd status')
```

```{r permanova__q0, comment="", message=FALSE, warning=FALSE}
beta_q0n_mat <- as.matrix(beta_q0n$S)
beta_q0n_filtered <- beta_q0n_mat[rownames(beta_q0n_mat) %in% sample_metadata$sample,
                        colnames(beta_q0n_mat) %in% sample_metadata$sample]
beta_q0n_dis <- as.dist(beta_q0n_filtered)

sample_metadata_ordered <- sample_metadata %>% 
  arrange(match(sample,labels(beta_q0n_dis))) %>% 
  column_to_rownames(., "sample")

all(sample_metadata_ordered$sample == labels(beta_q0n_dis))

betadisper(beta_q0n_dis, sample_metadata_ordered$Bd_status) %>% permutest(., pairwise = TRUE) 

adonis2(beta_q0n_dis ~ Bd_status+region+sex, 
        data = sample_metadata_ordered, 
        permutations = 999, by="margin") %>%
        broom::tidy() %>%
        tt()
```

## Neutral
```{r beta_div_nmds_neutral, fig.height=7, fig.width=12, fig.fullwidth=TRUE}
beta_q1n$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  mutate(Bd_status=factor(Bd_status,levels=c("Bd_positive", "Bd_negative")))%>%
  group_by(Bd_status) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot(aes(x = NMDS1, y = NMDS2, color = Bd_status)) +
    geom_point(size = 3, alpha = 0.9) +
    geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.5, show.legend = FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(face = "bold", size = 12),
      panel.background = element_blank(),
      axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 14),
      legend.position = "right", legend.box = "vertical"
    ) +
  labs(color='Bd status')
```

```{r permanova__q1, comment="", message=FALSE, warning=FALSE}
beta_q1n_mat <- as.matrix(beta_q1n$S)
beta_q1n_filtered <- beta_q1n_mat[rownames(beta_q1n_mat) %in% sample_metadata$sample,
                        colnames(beta_q1n_mat) %in% sample_metadata$sample]
beta_q1n_dis <- as.dist(beta_q1n_filtered)

sample_metadata_ordered <- sample_metadata %>% 
  arrange(match(sample,labels(beta_q1n_dis))) %>% 
  column_to_rownames(., "sample")

all(sample_metadata_ordered$sample == labels(beta_q1n_dis))

betadisper(beta_q1n_dis, sample_metadata_ordered$Bd_status) %>% permutest(., pairwise = TRUE) 

adonis2(beta_q1n_dis ~ Bd_status+region+sex, 
        data = sample_metadata_ordered, 
        permutations = 999, by="margin") %>%
        broom::tidy() %>%
        tt()
```

## Phylogenetic
```{r beta_div_nmds_phylo, fig.height=7, fig.width=12, fig.fullwidth=TRUE}
beta_q1p$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  mutate(Bd_status=factor(Bd_status,levels=c("Bd_positive", "Bd_negative")))%>%
  group_by(Bd_status) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot(aes(x = NMDS1, y = NMDS2, color = Bd_status)) +
    geom_point(size = 3, alpha = 0.9) +
    geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.5, show.legend = FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(face = "bold", size = 12),
      panel.background = element_blank(),
      axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 14),
      legend.position = "right", legend.box = "vertical"
    ) +
  labs(color='Bd status')
```
```{r permanova__q1p, comment="", message=FALSE, warning=FALSE}
beta_q1p_mat <- as.matrix(beta_q1p$S)
beta_q1p_filtered <- beta_q1p_mat[rownames(beta_q1p_mat) %in% sample_metadata$sample,
                        colnames(beta_q1p_mat) %in% sample_metadata$sample]
beta_q1p_dis <- as.dist(beta_q1p_filtered)

sample_metadata_ordered <- sample_metadata %>% 
  arrange(match(sample,labels(beta_q1p_dis))) %>% 
  column_to_rownames(., "sample")

all(sample_metadata_ordered$sample == labels(beta_q1p_dis))

betadisper(beta_q1p_dis, sample_metadata_ordered$Bd_status) %>% permutest(., pairwise = TRUE) 

adonis2(beta_q1p_dis ~ Bd_status+region+sex, 
        data = sample_metadata_ordered, 
        permutations = 999, by="margin") %>%
        broom::tidy() %>%
        tt()
```

## Functional
```{r beta_div_nmds_func, fig.height=7, fig.width=12, fig.fullwidth=TRUE}
beta_q1f$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  mutate(Bd_status=factor(Bd_status,levels=c("Bd_positive", "Bd_negative")))%>%
  group_by(Bd_status) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>% 
  ggplot(aes(x = NMDS1, y = NMDS2, color = Bd_status)) +
    geom_point(size = 3, alpha = 0.9) +
    geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.5, show.legend = FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(face = "bold", size = 12),
      panel.background = element_blank(),
      axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 14),
      legend.position = "right", legend.box = "vertical"
    ) +
  labs(color='Bd status')
```

```{r permanova__q1f, comment="", message=FALSE, warning=FALSE}
beta_q1f_mat <- as.matrix(beta_q1f$S)
beta_q1f_filtered <- beta_q1f_mat[rownames(beta_q1f_mat) %in% sample_metadata$sample,
                        colnames(beta_q1f_mat) %in% sample_metadata$sample]
beta_q1f_dis <- as.dist(beta_q1f_filtered)

sample_metadata_ordered <- sample_metadata %>% 
  arrange(match(sample,labels(beta_q1f_dis))) %>% 
  column_to_rownames(., "sample")

all(sample_metadata_ordered$sample == labels(beta_q1f_dis))

betadisper(beta_q1f_dis, sample_metadata_ordered$Bd_status) %>% permutest(., pairwise = TRUE) 

adonis2(beta_q1f_dis ~ Bd_status+region+sex, 
        data = sample_metadata_ordered, 
        permutations = 999, by="margin") %>%
        broom::tidy() %>%
        tt()
```
